"""Vercel serverless function — serves cached flight data from dataset.

Reads from data/flights_cache.json (pre-generated by scripts/refresh_flights.py).
Does NOT call SerpAPI directly — zero API cost per request.
"""

import json
import os
import sys
from http.server import BaseHTTPRequestHandler

# Allow imports from project root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

CACHE_FILE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data",
    "flights_cache.json",
)


class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        try:
            if not os.path.exists(CACHE_FILE):
                raise FileNotFoundError(
                    "Flight data not yet generated. Run: python3 scripts/refresh_flights.py"
                )

            with open(CACHE_FILE, "r", encoding="utf-8") as f:
                body = f.read().encode()

            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            # Still cache at CDN edge for performance, but this is free now
            self.send_header(
                "Cache-Control",
                "public, s-maxage=172800, stale-while-revalidate=172800",
            )
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(body)

        except Exception as exc:
            error = json.dumps({"error": str(exc)}).encode()
            self.send_response(500)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(error)
